### ISSUE TITLE
Decide on 1st party tech stack

### ISSUE THREAD

**Issue by JSimple** [eee-vvv/shirt-site#5]
## Todo
- [x] Unit testing (React testing library + Jest)

- [x] Integration testing (Cypress)
- [x] Database: PSQL (pg.js)
- [x] Client side frameworks (react.js , next.js)
- [x] State management framework (react context)
- [x] Deployment framework (next.js)
- [x] Server-side framework (express)

**Comment by JSimple** [comment]
## Todo
- [ ] Testing suite
- [ ] Database
- [ ] ORM?
- [ ] Server side frameworks
- [ ] State management framework 
- [ ] Deployment framework

**Comment by eee-vvv** [comment]
database = postgres
ORM = NO ORM
