### ISSUE TITLE
set up dev environment/spin up boilerplate app

### ISSUE THREAD

**Issue by JSimple** [eee-vvv/shirt-site#7]

**Comment by JSimple** [comment]
## TODO:
- [ ] change next.js/vercel account over to subysshirtsite@gmail.com
- [ ] create AWS free account
- [ ] create PSQL DB on AWS RDS
- [ ] connect DB to Next app using Serverless Edge Functions
